sudo: false
language: node_js
node_js:
- node
script:
- npm run build-all
- npm test
deploy:
  provider: npm
  email: niminghao804@gmail.com
  skip_cleanup: true
  api_key:
    secure: Z9f+BvwanDtcIrJaVHvGKoXkCDBYqRbEYSOdzWdhU4Ceg9BuMkwxodp9CwgiQMmawTbrYJwnXl5zEbJG32RyRfMXowlS0KD2p/nX9m27hh6ZofNqZjs0OipkKWHasL0+i2LJSrmx/UxQ47Bqepb/x3TdNBtY399UoJup3oBZcmZkx0WYxLFgs43wAkBjikVFxzj0aCuWShgC1++RaBO4TuNmMVLiQu4D85mAC8pFL8wpIl6LU7itQNQbVpHtqwyEVgmBQFHObycC12RF9GUHiOCbVB7yI5wNFqBRhRz9BgQ6TruD6s6k1Z6Tu/cUWqSFgsCzZ+Bxn8hWvzPR5cCoziNwx8EXxIdOqkMInqM4yYzxuUa2M52jTH6FCFISHSf+Rqj4EBix5OL/azU2N4/UUizXFvSRH/YI1SLQ3CCDqv+9+dSStc25h59bZGYI3nUXADmW3TNbRVezOFo+XXf8DF59NOIVsR1mFHRjHYj+k6iW5XoyCwoEgNIOs5qQYmwe7dCylAIx0K8U+sqfMIY3bFiiY0JjjXR9UXxz/4dPr9Mwmv7d08ygi5RXbFgQ+8gR0krAUYhhvG+wcysxqqGqBNiVbRH8v41DjJIhFsevaEO68/pDt9Un4Z7/JKW3P2PuWUCdPbrI59ASCfE1hM7AzHZ++0oFwagwgf/FLnF8Clo=
  on:
    tags: true
    repo: lemay/mws-api-lite
