sudo: false
language: node_js
node_js:
  - node
script:
  - npm run build-all
  - npm test
deploy:
  provider: npm
  email: niminghao804@gmail.com
  api_key:
    secure: GWiGsB5OdhEJVGQm4vJGUACKCsXdx5Aht/xyr4Ck8fNYsfTIly3SYElynNHqWvq6NVLOExNOG408w35dNpiHbqSvNdH/6ZIzrUb7rf+st1ZKxkRtbyWvSE9FXfzW9Wa5gKGyP4XLhnTUr9P1QJWjb3v4D0XuDx5cmmLuTxeWmIVTw1185NRdy0/79WfUwtN2o5q6NwjeosHr8136XIxddNOrDfdpBAsXYjaCe99VkPYb9lViDQM+tP7/4iBQY3KaNptVlfMKjp/sriqYZF9zy9F9OWJDHSUP2mpEd2yA7dF5EVf/ax4aDBioEL88KIDyDu9bZ7WnpvUsBqK0sEnf4bLnJYw2oTx4A+fBv/hilIMSxfWnxtETd2/tpLIbyyn5VdOvfQ1tCFw4NxLq9t6NxKzKA8mqRX7zKegJeow8lFblSRamGQW82bTWjQ+JpmvE4TvUJEuQEdfEaYTbWXfdDNtLe743hGNMXbDEw3wjkPsIl4BDkLb7VzPFuYwA1vivyhmAqwQ5jMKb41KR0QZXfI7kqgdCZ72C0b/A4KnIQdnSrN1vGzgfBsjlEnGw3DoB9qix4ZF8nNMNu2ys6r5n4ohgJCAvfyHV6ad3nme6HCnfBHReY0jqnUMOtxQb4NWl+M07zn6nV90ORpI8wxOpLm8wHPlHyrs1KRAWPF3ABtk=
  on:
    tags: true
    repo: lemay/mws-api-lite
